### ISSUE TITLE
Alumni team hidden

### ISSUE THREAD

**Issue by MichaelVessia** [adelphimathcs/about-us#1]
@b-stone , if you add the alumni team there are a few more people i can invite.

**Comment by bstone** [comment]
So the Alumni team was created. Were you not able to see it? Also, feel free to invite people. I am giving all students and alum admin privileges. Only faculty will have owner rights.

**Comment by MichaelVessia** [comment]
I wasn't able to see it, but it's now there.

**Comment by bstone** [comment]
Also, if you invite an alumni, feel free to put them in both Student and Alumni teams. My idea is to have the Alumni in both teams and when Students graduate, they will move up to Alumni.

**Comment by MichaelVessia** [comment]
I wasn't able to see the team because I wasn't on it.  Is there some kind of public/private setting on the teams? I can see the Owner team but not the Alumni team, even though I am on neither one.

**Comment by bstone** [comment]
Did you leave the team? I thought I put you on the alumni team. I am not sure how to organize the teams right now, so any suggestions would be great. As to the hidden issue, I don't think you can see another team in the organization.

**Comment by MichaelVessia** [comment]
I left the team to see if it would remain visible to me, and because I'm not yet an alum.  It is no longer visible to me.  Here is my current view of the teams.
![github_issue](https://cloud.githubusercontent.com/assets/5640057/8882007/d8d26c68-3211-11e5-9dac-db560b4281ee.jpg)

**Comment by bstone** [comment]
Ok. That is good to know. This is the first time I have used organizations so I am finding out all the little details as well. Maybe it's best to only view the owners and teams you are on.

**Comment by MichaelVessia** [comment]
Reply from GitHub staff:

Hi Michael,

Sorry for the trouble! If you're not an organization owner, you can only see teams you're a member of and the owners team. The owners team is special because that lets you know who the organization administrators are so you know who to contact if you need to be added to a team, etc. So the behavior you're seeing is expected in the current organization system.

Our engineers realize that this model doesn't fit some organizations and workflows however so we recently announced improved organization permissions which is in early access:

https://github.com/blog/2020-improved-organization-permissions

In particular, one of the new features is that all organization members can see all teams within the organization.

Note that only an organization owner can enroll an organization on the waitlist so if you think your organization would be interested, you'll need to ask a current owner to sign up.

**Comment by bstone** [comment]
I have requested early access.

**Comment by bstone** [comment]
Here is what GitHub said

> Hi Branden Stone, We’ve just enabled improved permissions for your organization: Adelphi University Math and Computer Science Department. Improvements include:
> - _Default repository access levels._ Organization owners can now set a default repository access level for all members. If you run a more open organization, this allows you to grant every member access to every repository without making them all Owners or creating a giant catch-all team.
> - _Team maintainers._ Members can now be made “maintainers” of specific teams. A team maintainer can manage that team’s members without and owner’s approval.
> - _Improved team visibility and communication._ Owners can make teams visible to all organization members. If you make every team in your organization visible, your members will be able to use team @ mentions across your organization. You can also create "secret teams," which are only visible to the people you add to them.
> - _Outside collaborators._ Owners can now add people who are not members of the organization (e.g. interns, contractors, etc.) directly to repositories.
> 
> The end result should be fewer owners and a permissions model that helps to improve collaboration. You can also read the documentation for more detail. Technical support: If you need help with any technical issues, please check out our documentation and email us at support@github.com. Thanks, ~The GitHub organizations team

**Comment by bstone** [comment]
@MichaelVessia, do you want to be a team maintainer for the Student team?

**Comment by MichaelVessia** [comment]
Sure, sounds good to me.

**Comment by bstone** [comment]
So I have not found out how to do this yet, but I will look into it. As to the issue of creating repos, I think I have fixed that. Let me know if it does not work.

**Comment by bstone** [comment]
OK, this is done now. @MichaelVessia, you are now a team maintainer for the student team. I will let you google and figure out what that means. Or you can look here: https://help.github.com/articles/giving-team-maintainer-permissions-to-an-organization-member-early-access-program/

**Comment by bstone** [comment]
I felt like I needed to close the issue again.
