### ISSUE TITLE
Project Euler hacked again... 

### ISSUE THREAD

**Issue by MichaelVessia** [adelphimathcs/about-us#5]
With ProjectEuler being hacked and temporarily unable to accept problem submissions, I've been solving problems on a site called https://leetcode.com .  The problems are more data structures and algorithms focused, as compared to ProjectEuler which gets very math heavy very fast.  I also log in to https://codewars.com every once in a while and solve some problems.  Just figured I'd post this incase anyone else was bored and looking for some more problem solving sites.

**Comment by bstone** [comment]
Why would people do this? Thanks for sharing the other ideas. I think @adelphimathcs/students and @adelphimathcs/alumni would be interested in this information.

**Comment by MichaelVessia** [comment]
I expect it's a form of Watering Hole attack.  Attackers know that
developers from many prolific companies frequent the site, and it's
certainly easier to hack something like Project Euler than to attempt to
hack the company directly.  That or they got frustrated that they couldn't
solve the problems so they took it down :)

On Fri, Aug 7, 2015 at 3:18 PM, Branden Stone notifications@github.com
wrote:

> Why would people do this? Thanks for sharing the other ideas. I think
> @adelphimathcs/students
> https://github.com/orgs/adelphimathcs/teams/students and
> @adelphimathcs/alumni https://github.com/orgs/adelphimathcs/teams/alumni
> would be interested in this information.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/adelphimathcs/about-us/issues/5#issuecomment-128799278
> .

## 

_Michael Vessia Jr._
Adelphi University, Computer Science and Mathematics, 2016

**Comment by MattMatero** [comment]
I believe they were using the site to serve malware and ads to regular users. Nothing crazy, they probably just picked PE since it's fairly popular and I doubt has cutting edge security.

**Comment by MichaelVessia** [comment]
Project Euler is back online!
